### ISSUE TITLE
Block Generation 

### ISSUE THREAD

**Issue by nimajneb5000** [kinfoundation/kin-rfcs#8]
Implement proof of stake or hybrid POW/POS block generation. A system similar to Peercoin's could feasibly be have the Kin Foundation as central authority.  Overall, this would have the advantage of drawing capital into the ecosystem, rewarding stakeholders, and controlling inflation.

**Comment by oryband** [comment]
Thanks for the proposal, but this issue is not a comment or an update proposal for any RFC. Please keep generic product discussions where they should be: [/r/KinFoundation](https://www.reddit.com/r/KinFoundation/) or on our [Telegram groups](https://t.me/kinfoundation).

Closing this issue.
